# Generated by Django 4.2.2 on 2023-07-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
    ]
