# Generated by Django 4.2.2 on 2023-07-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0002_auto_20230704_1717'),
    ]

    operations = [
    ]
