# Generated by Django 4.2.2 on 2023-07-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0003_auto_20230704_1725'),
    ]

    operations = [
    ]
