# Generated by Django 4.2.2 on 2023-07-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0004_auto_20230705_0926'),
    ]

    operations = [
    ]
