# Generated by Django 4.2.2 on 2023-07-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0005_auto_20230705_1037'),
    ]

    operations = [
    ]
