# Generated by Django 4.2.2 on 2023-07-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0006_auto_20230710_1237'),
    ]

    operations = [
    ]
