# Generated by Django 4.2.2 on 2023-07-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0007_auto_20230710_1309'),
    ]

    operations = [
    ]
