# Generated by Django 4.2.2 on 2023-07-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0008_auto_20230710_1607'),
    ]

    operations = [
    ]
