# Generated by Django 4.2.2 on 2023-07-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0009_auto_20230710_1718'),
    ]

    operations = [
    ]
