# Generated by Django 4.2.2 on 2023-07-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0010_auto_20230711_0911'),
    ]

    operations = [
    ]
